# Generated by Django 5.2.1 on 2025-07-09 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, unique=True)),
                ('total_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('pallet_no', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('re_order_level', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('Modify', 'Modify'), ('Delete', 'Delete')], default='Modify', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockUpload',
            fields=[
                ('whs_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('batch', models.CharField(max_length=20)),
                ('bin', models.CharField(max_length=20)),
                ('pallet', models.CharField(max_length=20)),
                ('p_mat', models.CharField(max_length=20)),
                ('inspection', models.CharField(max_length=20)),
                ('stock_type', models.CharField(max_length=20)),
                ('wps', models.CharField(max_length=20)),
                ('doc_no', models.CharField(max_length=20)),
                ('pallet_status', models.CharField(default='Not planned', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, default='vendor_images/default.jpg', null=True, upload_to='vendor_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('whs_no', models.IntegerField(primary_key=True, serialize=False)),
                ('whs_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phn_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('manager', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouse_images/')),
            ],
        ),
        migrations.CreateModel(
            name='YardHdr',
            fields=[
                ('truck_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('whs_no', models.CharField(max_length=5, unique=True)),
                ('truck_type', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_phn_no', models.CharField(max_length=10)),
                ('po_no', models.CharField(max_length=10)),
                ('truck_date', models.DateField()),
                ('truck_time', models.TimeField()),
                ('seal_no', models.CharField(max_length=10)),
                ('yard_scan', models.CharField(max_length=10)),
                ('truck_status', models.CharField(default='Not planned', editable=False, max_length=10)),
                ('is_the_lock_secure', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_truck_clean', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_driver_safe', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_pallet_stable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_temperature_ideal', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_ac_working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('does_the_truck_have_a_good_odor', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_truck_dock_level_ok', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_no', models.CharField(max_length=100, unique=True)),
                ('capacity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product')),
            ],
        ),
        migrations.CreateModel(
            name='TruckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_date', models.DateField(auto_now_add=True)),
                ('truck_time', models.TimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(default='Not planned', max_length=20)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('truck_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.yardhdr')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_phn_no', models.CharField(max_length=10)),
                ('truck_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.yardhdr')),
            ],
        ),
    ]
