# Generated by Django 5.2.3 on 2025-07-03 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('pallet_no', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('re_order_level', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='YardHdr',
            fields=[
                ('truck_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('whs_no', models.CharField(max_length=5, unique=True)),
                ('truck_type', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_phn_no', models.CharField(max_length=10)),
                ('po_no', models.CharField(max_length=10)),
                ('truck_date', models.DateField()),
                ('truck_time', models.TimeField()),
                ('seal_no', models.CharField(max_length=10)),
                ('yard_scan', models.CharField(max_length=10)),
                ('truck_status', models.CharField(default='Not planned', editable=False, max_length=10)),
                ('is_the_lock_secure', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_truck_clean', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_driver_safe', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_pallet_stable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_temperature_ideal', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_ac_working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('does_the_truck_have_a_good_odor', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_the_truck_dock_level_ok', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TruckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_date', models.DateField(auto_now_add=True)),
                ('truck_time', models.TimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(default='Not planned', max_length=20)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('truck_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.yardhdr')),
            ],
        ),
    ]
