# Generated by Django 5.2.1 on 2025-06-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YardHdr',
            fields=[
                ('whs_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('truck_no', models.CharField(max_length=10)),
                ('truck_type', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_phn_no', models.CharField(max_length=15)),
                ('po_no', models.CharField(max_length=20)),
                ('truck_date', models.DateField()),
                ('truck_time', models.TimeField()),
                ('seal_no', models.CharField(max_length=20)),
                ('yard_scan', models.CharField(max_length=20)),
                ('truck_status', models.CharField(default='Not planned', editable=False, max_length=20)),
            ],
        ),
    ]
