# Generated by Django 5.2.3 on 2025-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='scanned_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
