# Generated by Django 5.2.1 on 2025-08-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockupload',
            old_name='wps',
            new_name='item_number',
        ),
    ]
