# Generated by Django 5.2.1 on 2025-09-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='warehouse',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='rf_dispatch.warehouse'),
        ),
    ]
