# Generated by Django 5.2.1 on 2025-08-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbounddeliveryitem',
            old_name='total_unit_price',
            new_name='unit_total_price',
        ),
    ]
