# Generated by Django 5.2.1 on 2025-08-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbounddelivery',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbounddeliveries', to='rf_dispatch.vendor'),
        ),
    ]
