# Generated by Django 5.2.1 on 2025-09-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='customer_number',
            new_name='invoice_number',
        ),
    ]
