# Generated by Django 5.2.3 on 2025-07-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putaway',
            name='confirmed_at',
        ),
        migrations.AlterField(
            model_name='putaway',
            name='created_at',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='putaway',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
