# Generated by Django 5.2.1 on 2025-09-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_no', models.CharField(max_length=100, unique=True)),
                ('hu_numbers', models.TextField()),
                ('confirmation_numbers', models.TextField()),
                ('linked_trucks', models.TextField()),
                ('loading_date', models.DateField()),
                ('loading_supervisor', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
