# Generated by Django 5.2.1 on 2025-08-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ship_to_address',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ship_to_company_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ship_to_email',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ship_to_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ship_to_phone',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ship_to_website',
        ),
    ]
