# Generated by Django 5.2.3 on 2025-07-09 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, unique=True)),
                ('total_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, default='vendor_images/default.jpg', null=True, upload_to='vendor_images/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='action',
            field=models.CharField(choices=[('Modify', 'Modify'), ('Delete', 'Delete')], default='Modify', max_length=20),
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_no', models.CharField(max_length=100, unique=True)),
                ('capacity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product')),
            ],
        ),
    ]
