# Generated by Django 5.2.1 on 2025-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='min_quantity',
            field=models.IntegerField(default=5, help_text='Minimum quantity before low stock warning'),
        ),
    ]
