# Generated by Django 5.2.1 on 2025-09-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='whs_no',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
