# Generated by Django 5.2.1 on 2025-06-17 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yardhdr',
            name='Seal_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='as_the_AC_is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='does_the_truck_have_a_good_odor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_driver_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_lock_secure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_pallet_stable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_temperature_ideal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_track_dock_level_is_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_truck_clean',
            field=models.BooleanField(default=False),
        ),
    ]
