# Generated by Django 5.2.3 on 2025-08-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='picking',
            name='picking_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
