# Generated by Django 5.2.1 on 2025-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='pallet_no',
            field=models.CharField(default=0, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
