# Generated by Django 5.2.1 on 2025-09-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packingmaterial',
            old_name='name',
            new_name='material',
        ),
    ]
