# Generated by Django 5.2.1 on 2025-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
