# Generated by Django 5.2.1 on 2025-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('unused', 'Unused'), ('assigned', 'Assigned')], default='unused', max_length=20),
        ),
    ]
