# Generated by Django 5.2.1 on 2025-09-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucklog',
            name='time_taken',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
