# Generated by Django 5.2.1 on 2025-10-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PutToLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('bin_id', models.CharField(max_length=100)),
                ('confirm_bin_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='whs_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='rf_dispatch.warehouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='whs_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rf_dispatch.warehouse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='warehouse',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='rf_dispatch.warehouse'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='whs_no',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='rf_dispatch.warehouse'),
        ),
    ]
