# Generated by Django 5.2.1 on 2025-08-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='net_price',
        ),
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='qty_issued',
        ),
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='qty_order',
        ),
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='total_unit_price',
        ),
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='vol_per_item',
        ),
    ]
