# Generated by Django 5.2.3 on 2025-07-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='action',
            field=models.CharField(choices=[('Modify', 'Modify'), ('Delete', 'Delete')], default='Modify', max_length=20),
        ),
    ]
