# Generated by Django 5.2.1 on 2025-08-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inbound_delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gr', to='rf_dispatch.inbounddelivery')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rf_dispatch.goodsreceipt')),
                ('inbound_delivery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gr_items', to='rf_dispatch.inbounddeliveryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PostGoodsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgi_no', models.CharField(max_length=50, unique=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pgi', to='rf_dispatch.outbounddelivery')),
            ],
        ),
    ]
