# Generated by Django 5.2.3 on 2025-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
