# Generated by Django 5.2.1 on 2025-09-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('port_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
