# Generated by Django 5.2.3 on 2025-09-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binlog',
            name='quantity_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='binlog',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='binlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
