# Generated by Django 5.2.3 on 2025-08-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
