# Generated by Django 5.2.1 on 2025-08-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.purchaseorder'),
        ),
    ]
