# Generated by Django 5.2.1 on 2025-07-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='warehouse_images/'),
        ),
    ]
