# Generated by Django 5.2.1 on 2025-09-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sorted', 'Sorted')], default='Pending', max_length=50)),
                ('sorted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.outbounddelivery')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.pallet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.product')),
                ('so_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.salesordercreation')),
                ('warehouse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.warehouse')),
            ],
            options={
                'ordering': ['-sorted_at'],
                'indexes': [models.Index(fields=['status'], name='rf_dispatch_status_5af142_idx'), models.Index(fields=['outbound'], name='rf_dispatch_outboun_e57d4f_idx')],
            },
        ),
    ]
