# Generated by Django 5.2.1 on 2025-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(max_length=100)),
                ('no_of_pallets', models.IntegerField()),
                ('linked_customers', models.TextField()),
                ('pgid_hus', models.TextField()),
                ('overflow_area', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
