# Generated by Django 5.2.1 on 2025-08-29 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_rename_wps_stockupload_item_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='shelves',
        ),
        migrations.AddField(
            model_name='bin',
            name='bin_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
