# Generated by Django 5.2.1 on 2025-09-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_profile_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='whs_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rf_dispatch.warehouse'),
        ),
    ]
