# Generated by Django 5.2.3 on 2025-09-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_bin_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='sub_category',
        ),
    ]
