# Generated by Django 5.2.1 on 2025-07-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_warehouse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='image',
        ),
    ]
