# Generated by Django 5.2.1 on 2025-09-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
