# Generated by Django 5.2.1 on 2025-08-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_rename_total_unit_price_outbounddeliveryitem_unit_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbounddeliveryitem',
            old_name='net_price',
            new_name='net_total_price',
        ),
    ]
