# Generated by Django 5.2.1 on 2025-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_yardhdr_seal_number_yardhdr_as_the_ac_is_working_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(max_length=20)),
                ('is_the_lock_secure', models.BooleanField(default=False)),
                ('is_the_truck_clean', models.BooleanField(default=False)),
                ('is_the_driver_safe', models.BooleanField(default=False)),
                ('seal_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_the_pallet_stable', models.BooleanField(default=False)),
                ('is_the_temperature_ideal', models.BooleanField(default=False)),
                ('is_the_ac_working', models.BooleanField(default=False)),
                ('does_the_truck_have_a_good_odor', models.BooleanField(default=False)),
                ('is_the_truck_dock_level_ok', models.BooleanField(default=False)),
            ],
        ),
    ]
