# Generated by Django 5.2.1 on 2025-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_pallet_pallet_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='is_scanned',
            new_name='is_child_hu',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='capacity',
        ),
        migrations.AddField(
            model_name='pallet',
            name='p_mat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
