# Generated by Django 5.2.1 on 2025-09-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_warehouse_whs_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='whs_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
