# Generated by Django 5.2.1 on 2025-08-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_remove_picking_created_by_picking_picking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='picking_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
