# Generated by Django 5.2.1 on 2025-09-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_pallet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.pallet'),
        ),
    ]
