# Generated by Django 5.2.1 on 2025-09-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_inventory_options_inventory_min_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='min_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
