# Generated by Django 5.2.3 on 2025-08-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_inbounddeliveryproduct_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PutawayTask',
        ),
        migrations.AlterField(
            model_name='putaway',
            name='putaway_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
