# Generated by Django 5.2.3 on 2025-08-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_picking_created_by_alter_picking_picking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_delivery_number', models.CharField(max_length=50, unique=True)),
                ('delivery_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('purchase_order_number', models.CharField(max_length=50)),
                ('receiving_plant', models.CharField(max_length=100)),
                ('material_code', models.CharField(max_length=50)),
                ('material_description', models.CharField(max_length=200)),
                ('quantity_delivered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_status', models.CharField(max_length=50)),
                ('storage_location', models.CharField(max_length=100)),
                ('carrier_info', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
