# Generated by Django 5.2.1 on 2025-09-23 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_bin_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pallet_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='rf_dispatch.pallet'),
        ),
    ]
