# Generated by Django 5.2.1 on 2025-08-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_product_po_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='po_number',
        ),
    ]
