# Generated by Django 5.2.3 on 2025-09-23 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_binlog_quantity_changed_binlog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
