# Generated by Django 5.2.1 on 2025-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(max_length=15)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('po_date', models.DateField(auto_now_add=True)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('customer_number', models.CharField(max_length=50)),
                ('vendor_company_name', models.CharField(max_length=255)),
                ('vendor_contact_name', models.CharField(max_length=255)),
                ('vendor_phone', models.CharField(max_length=15)),
                ('vendor_address', models.TextField()),
                ('vendor_website', models.URLField(blank=True, null=True)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('ship_to_name', models.CharField(max_length=255)),
                ('ship_to_company_name', models.CharField(max_length=255)),
                ('ship_to_address', models.TextField()),
                ('ship_to_phone', models.CharField(max_length=15)),
                ('ship_to_email', models.EmailField(max_length=254)),
                ('ship_to_website', models.URLField(blank=True, null=True)),
                ('item_number', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
