# Generated by Django 5.2.3 on 2025-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_pallet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='confirmed_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
