# Generated by Django 5.2.1 on 2025-08-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_remove_outbounddelivery_batch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbounddelivery',
            name='del_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outbounddelivery',
            name='ord_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
