# Generated by Django 5.2.3 on 2025-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_picking_pallet_alter_picking_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='pallet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picking',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
