# Generated by Django 5.2.1 on 2025-09-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_weighingscale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeighingScale',
            new_name='WeighingScaleConfiguration',
        ),
    ]
