# Generated by Django 5.2.3 on 2025-09-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_bin_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
