# Generated by Django 5.2.1 on 2025-10-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_puttolight_alter_inventory_whs_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingmaterial',
            name='whs_no',
        ),
    ]
