# Generated by Django 5.2.3 on 2025-07-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_remove_putaway_confirmed_at_alter_putaway_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='putaway',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='putaway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
