# Generated by Django 5.2.3 on 2025-08-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_pallet_created_at_alter_pallet_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='existing_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
