# Generated by Django 5.2.1 on 2025-09-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_rename_name_packingmaterial_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockupload',
            old_name='wps',
            new_name='item_number',
        ),
    ]
