# Generated by Django 5.2.1 on 2025-09-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_rename_wps_stockupload_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
