# Generated by Django 5.2.1 on 2025-08-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_picking_picking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
