# Generated by Django 5.2.3 on 2025-08-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_alter_customers_customer_id'),
        ('rf_dispatch', '0003_remove_product_po_number'),
    ]

    operations = [
    ]
