# Generated by Django 5.2.1 on 2025-06-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_truckinspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yardhdr',
            name='Seal_number',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='as_the_AC_is_working',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='does_the_truck_have_a_good_odor',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='is_the_driver_safe',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='is_the_lock_secure',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='is_the_pallet_stable',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='is_the_temperature_ideal',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='is_the_track_dock_level_is_ok',
        ),
        migrations.RemoveField(
            model_name='yardhdr',
            name='is_the_truck_clean',
        ),
    ]
