# Generated by Django 5.2.3 on 2025-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
