# Generated by Django 5.2.1 on 2025-08-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_rename_is_scanned_pallet_is_child_hu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='is_child_hu',
        ),
    ]
