# Generated by Django 5.2.1 on 2025-09-23 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_product_pallet_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
