# Generated by Django 5.2.1 on 2025-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_warehouse_whs_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresponse',
            name='answer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
    ]
