# Generated by Django 5.2.1 on 2025-10-03 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_product_whs_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='whs_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='rf_dispatch.warehouse'),
        ),
    ]
