# Generated by Django 5.2.3 on 2025-09-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_bin_confirmed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='confirmed_at',
        ),
    ]
