# Generated by Django 5.2.3 on 2025-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_purchaseorder_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='picking_type',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default=True, max_length=50),
        ),
    ]
