# Generated by Django 5.2.3 on 2025-09-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_bin_location'),
    ]

    operations = [
      migrations.AlterField(
            model_name='bin',
            name='location',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    
    ]
