# Generated by Django 5.2.3 on 2025-09-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_bin_created_at_bin_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binlog',
            name='whs_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rf_dispatch.warehouse'),
        ),
    ]
