# Generated by Django 5.2.1 on 2025-10-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_remove_packingmaterial_whs_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='whs_no',
        ),
    ]
