# Generated by Django 5.2.1 on 2025-07-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('products', models.CharField(max_length=255)),
                ('existing_quantity', models.IntegerField()),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('whs_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='rf_dispatch.warehouse')),
            ],
        ),
    ]
