# Generated by Django 5.2.1 on 2025-08-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_rename_net_price_outbounddeliveryitem_net_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbounddeliveryitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='outbounddeliveryitem',
            name='product_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
