# Generated by Django 5.2.3 on 2025-09-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_picking_pallet_alter_picking_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.pallet'),
        ),
        migrations.AlterField(
            model_name='picking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product'),
        ),
    ]
