# Generated by Django 5.2.1 on 2025-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_stockupload_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='existing_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
