# Generated by Django 5.2.1 on 2025-09-05 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_inventory_options_alter_inventory_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='putaway',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rf_dispatch.bin'),
        ),
        migrations.AddField(
            model_name='putaway',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rf_dispatch.product'),
        ),
        migrations.AddField(
            model_name='putaway',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rf_dispatch.warehouse'),
        ),
    ]
