# Generated by Django 5.2.1 on 2025-08-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='doc_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='inspection',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='p_mat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='pallet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='pallet_status',
            field=models.CharField(default='Not planned', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='stock_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='wps',
            field=models.CharField(max_length=100),
        ),
    ]
