# Generated by Django 5.2.3 on 2025-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_customers_inventory_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
