# Generated by Django 5.2.3 on 2025-08-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_salesorderitem_existing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='existing_quantity',
            field=models.IntegerField(),
        ),
    ]
