# Generated by Django 5.2.1 on 2025-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_stockupload_pallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='status',
        ),
        migrations.AddField(
            model_name='pallet',
            name='pallet_no',
            field=models.CharField(default='', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='pallet',
            field=models.CharField(blank=True, default='Not assigned', max_length=50, null=True),
        ),
    ]
