# Generated by Django 5.2.1 on 2025-09-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_rename_weighingscale_weighingscaleconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeighingScaleConfiguration',
        ),
    ]
