# Generated by Django 5.2.1 on 2025-09-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_purchaseitem_warehouse_alter_purchaseitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardhdr',
            name='whs_no',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.warehouse'),
        ),
    ]
