# Generated by Django 5.2.1 on 2025-09-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_alter_inspectionresponse_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionresponse',
            name='answer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='whs_no',
            field=models.CharField(max_length=50),
        ),
    ]
