# Generated by Django 5.2.3 on 2025-09-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_alter_picking_pallet_alter_picking_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packeditem',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rf_dispatch.pallet'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='rf_dispatch.pallet'),
        ),
    ]
