# Generated by Django 5.2.1 on 2025-10-03 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_alter_inventory_whs_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='whs_no',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='rf_dispatch.warehouse'),
            preserve_default=False,
        ),
    ]
