# Generated by Django 5.2.1 on 2025-10-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_remove_pallet_whs_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='whs_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='whs_no',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='whs_no',
        ),
    ]
