# Generated by Django 5.2.1 on 2025-09-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_alter_bin_existing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
