# Generated by Django 5.2.1 on 2025-09-22 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_remove_pallet_status_pallet_pallet_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pallet_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rf_dispatch.pallet'),
        ),
    ]
