# Generated by Django 5.2.1 on 2025-09-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_alter_product_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportDispatch',
        ),
    ]
