# Generated by Django 5.2.1 on 2025-08-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_alter_purchaseorder_company_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbounddelivery',
            name='so_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_deliveries', to='rf_dispatch.salesordercreation'),
        ),
    ]
