# Generated by Django 5.2.1 on 2025-09-05 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_putaway_bin_putaway_product_putaway_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putaway',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rf_dispatch.pallet'),
        ),
    ]
