# Generated by Django 5.2.1 on 2025-08-14 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_remove_pallet_is_child_hu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
