# Generated by Django 5.2.1 on 2025-08-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_truckquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckQuestion',
        ),
    ]
