# Generated by Django 5.2.3 on 2025-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_alter_salesorderitem_existing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='existing_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
