# Generated by Django 5.2.1 on 2025-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_alter_stockupload_batch_alter_stockupload_doc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='whs_no',
            field=models.CharField(max_length=100),
        ),
    ]
