# Generated by Django 5.2.1 on 2025-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_rename_product_outbounddeliveryitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordercreation',
            name='str_loc',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
