# Generated by Django 5.2.1 on 2025-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_warehouse_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, unique=True)),
                ('total_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
