# Generated by Django 5.2.3 on 2025-08-20 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_merge_20250820_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putaway',
            name='confirmed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
