# Generated by Django 5.2.1 on 2025-06-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_remove_yardhdr_seal_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckinspection',
            name='truck_no',
        ),
    ]
