# Generated by Django 5.2.1 on 2025-08-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_salesordercreation_str_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='dlv_it_no',
        ),
    ]
