# Generated by Django 5.2.1 on 2025-09-05 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_alter_putaway_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordercreation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesordercreation',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesordercreation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesordercreation',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesordercreation',
            name='whs_address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='salesordercreation',
            name='whs_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='rf_dispatch.warehouse'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
