# Generated by Django 5.2.3 on 2025-08-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_alter_salesorderitem_existing_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='total_quantity',
            new_name='existing_quantity',
        ),
    ]
