# Generated by Django 5.2.1 on 2025-09-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_inspectionquestion'),
        ('rf_dispatch', '0005_alter_putaway_pallet'),
    ]

    operations = [
    ]
