# Generated by Django 5.2.1 on 2025-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_alter_outbounddelivery_so_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbounddelivery',
            name='dlv_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
