# Generated by Django 5.2.1 on 2025-06-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_remove_truckinspection_truck_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckInspection',
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='does_the_truck_have_a_good_odor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_ac_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_driver_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_lock_secure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_pallet_stable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_temperature_ideal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_truck_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='is_the_truck_dock_level_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yardhdr',
            name='seal_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
