# Generated by Django 5.2.1 on 2025-10-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_remove_category_whs_no_remove_product_whs_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='whs_no',
        ),
    ]
