# Generated by Django 5.2.1 on 2025-09-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_delete_exportdispatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='loading_date',
            new_name='planned_dispatch_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='confirmation_numbers',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='hu_numbers',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='linked_trucks',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='loading_supervisor',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='status',
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_status',
            field=models.CharField(default='Planned', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='truck',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.truck'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='yard_hdr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.yardhdr'),
        ),
    ]
