# Generated by Django 5.2.3 on 2025-09-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_alter_bin_created_by_alter_bin_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
