# Generated by Django 5.2.3 on 2025-09-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_remove_bin_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
