# Generated by Django 5.2.1 on 2025-09-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_alter_product_pallet_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pallet_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
