# Generated by Django 5.2.3 on 2025-09-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_remove_putaway_confirmed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binlog',
            old_name='destination_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='quantity_changed',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='whs_no',
        ),
    ]
