# Generated by Django 5.2.3 on 2025-08-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_alter_putaway_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
