# Generated by Django 5.2.1 on 2025-09-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_delete_truckquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbounddelivery',
            name='carrier_info',
        ),
        migrations.RemoveField(
            model_name='inbounddelivery',
            name='gr_date',
        ),
        migrations.RemoveField(
            model_name='inbounddelivery',
            name='storage_location',
        ),
    ]
