# Generated by Django 5.2.3 on 2025-08-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_alter_picking_picking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='picking_type',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Inbound', max_length=50),
        ),
    ]
