# Generated by Django 5.2.3 on 2025-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_alter_packeditem_pallet_alter_packing_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='picking',
            name='updated_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
