# Generated by Django 5.2.1 on 2025-07-04 08:46

import django.db.models.deletion
import rf_dispatch.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0005_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('pallet_no', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('re_order_level', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_no', models.CharField(max_length=100, unique=True)),
                ('product', models.CharField(blank=True, null=True, verbose_name=rf_dispatch.models.Product)),
                ('capacity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
