# Generated by Django 5.2.1 on 2025-07-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_remove_bin_existing_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='existing_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
