# Generated by Django 5.2.1 on 2025-09-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_rename_loading_date_shipment_planned_dispatch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='yard_hdr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
