# Generated by Django 5.2.3 on 2025-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_alter_purchaseorder_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
