# Generated by Django 5.2.1 on 2025-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_alter_pallet_created_by_alter_pallet_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='updated_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
