# Generated by Django 5.2.3 on 2025-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_alter_picking_picking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='picking_type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='Inbound', max_length=50),
        ),
    ]
