# Generated by Django 5.2.1 on 2025-07-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_product_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product'),
        ),
    ]
