# Generated by Django 5.2.3 on 2025-08-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_rename_total_quantity_inventory_existing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='existing_quantity',
            field=models.IntegerField(),
        ),
    ]
