# Generated by Django 5.2.3 on 2025-09-01 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_bin_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='bin',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='rf_dispatch.subcategory'),
        ),
    ]
