# Generated by Django 5.2.1 on 2025-10-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_remove_bin_whs_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binlog',
            name='whs_no',
        ),
    ]
