# Generated by Django 5.2.1 on 2025-08-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_remove_outbounddelivery_dlv_it_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbounddeliveryitem',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
