# Generated by Django 5.2.3 on 2025-09-22 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_alter_bin_created_by_alter_bin_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('existing_quantity', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rf_dispatch.bin')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.subcategory')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('whs_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.warehouse')),
            ],
        ),
    ]
