# Generated by Django 5.2.1 on 2025-09-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0004_inspectionquestion'),
        ('rf_dispatch', '0006_salesordercreation_created_at_and_more'),
    ]

    operations = [
    ]
