# Generated by Django 5.2.1 on 2025-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_delete_truckinspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardhdr',
            name='does_the_truck_have_a_good_odor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='is_the_ac_working',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='is_the_driver_safe',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='is_the_lock_secure',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='is_the_pallet_stable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='is_the_temperature_ideal',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='is_the_truck_clean',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='is_the_truck_dock_level_ok',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
