# Generated by Django 5.2.3 on 2025-09-22 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_binlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='bin_type',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='existing_quantity',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='binlog',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='binlog',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binlog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='binlog',
            name='whs_no',
            field=models.CharField(max_length=50),
        ),
    ]
