# Generated by Django 5.2.3 on 2025-09-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_remove_putaway_confirmed_at_putaway_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='putaway',
            name='confirmed_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
