# Generated by Django 5.2.1 on 2025-09-05 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_merge_20250905_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbounddeliveryitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='outbounddeliveryitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='outbounddeliveryitem',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_items', to='rf_dispatch.product'),
            preserve_default=False,
        ),
    ]
