# Generated by Django 5.2.1 on 2025-09-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_alter_shipment_yard_hdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='truck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
