# Generated by Django 5.2.3 on 2025-08-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_alter_picking_picking_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(max_length=50)),
                ('p_mat', models.CharField(max_length=100)),
                ('del_no', models.CharField(max_length=50)),
                ('gross_wt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_wt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='rf_dispatch.picking')),
            ],
        ),
        migrations.CreateModel(
            name='PackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(max_length=50)),
                ('p_mat', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rf_dispatch.packing')),
            ],
        ),
    ]
