# Generated by Django 5.2.1 on 2025-08-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_alter_outbounddeliveryitem_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesordercreation',
            old_name='str_loc',
            new_name='whs_address',
        ),
    ]
