# Generated by Django 5.2.1 on 2025-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_alter_pallet_created_by_alter_pallet_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
