# Generated by Django 5.2.1 on 2025-06-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_alter_yardhdr_does_the_truck_have_a_good_odor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yardhdr',
            name='seal_number',
        ),
    ]
