# Generated by Django 5.2.1 on 2025-09-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_inspectionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='inspectionanswer',
            name='created_at',
        ),
    ]
