# Generated by Django 5.2.3 on 2025-07-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_alter_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
    ]
