# Generated by Django 5.2.1 on 2025-07-04 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0007_alter_pallet_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='scanned_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='updated_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
