# Generated by Django 5.2.1 on 2025-06-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_remove_yardhdr_seal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardhdr',
            name='is_the_truck_dock_level_ok',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=3),
        ),
    ]
