# Generated by Django 5.2.1 on 2025-09-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_remove_inspectionanswer_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InspectionAnswer',
        ),
    ]
