# Generated by Django 5.2.3 on 2025-08-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_packing_packeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='picking',
        ),
    ]
