# Generated by Django 5.2.3 on 2025-08-22 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_alter_purchaseorder_customer_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_id', models.CharField(max_length=30)),
                ('customer_code', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('net_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirm', 'Confirm'), ('Cancel', 'Cancel'), ('Edit', 'Edit'), ('Delivery', 'Delivery')], default='Draft', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('whs_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='rf_dispatch.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('so_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rf_dispatch.salesordercreation')),
            ],
        ),
    ]
