# Generated by Django 5.2.1 on 2025-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_remove_outbounddeliveryitem_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbounddeliveryitem',
            name='vol_per_item',
        ),
        migrations.AlterField(
            model_name='outbounddelivery',
            name='dlv_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='outbounddeliveryitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outbounddeliveryitem',
            name='dlv_it_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outbounddeliveryitem',
            name='qty_issued',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='outbounddeliveryitem',
            name='qty_order',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='outbounddeliveryitem',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outbounddeliveryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
