# Generated by Django 5.2.1 on 2025-08-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_rename_str_loc_salesordercreation_whs_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesordercreation',
            name='net_total_price',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product'),
        ),
    ]
