# Generated by Django 5.2.3 on 2025-08-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_remove_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='existing_quantity',
            new_name='total_quantity',
        ),
    ]
