# Generated by Django 5.2.1 on 2025-07-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='products',
        ),
    ]
