# Generated by Django 5.2.1 on 2025-09-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_alter_shipment_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rf_dispatch.truck'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='yard_hdr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rf_dispatch.yardhdr'),
        ),
    ]
