# Generated by Django 5.2.3 on 2025-09-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_putaway_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='confirmed_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
