# Generated by Django 5.2.1 on 2025-09-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0008_alter_pallet_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pallet_no',
        ),
        migrations.AddField(
            model_name='product',
            name='pallet_no',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='rf_dispatch.pallet'),
        ),
    ]
