# Generated by Django 5.2.3 on 2025-08-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_salesordercreation_salesorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordercreation',
            name='address',
            field=models.TextField(default=True, max_length=50),
        ),
    ]
