# Generated by Django 5.2.1 on 2025-08-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_remove_salesordercreation_net_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordercreation',
            name='net_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
