# Generated by Django 5.2.3 on 2025-09-15 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_picking_confirmed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picking',
            old_name='location',
            new_name='destination_location',
        ),
        migrations.AddField(
            model_name='picking',
            name='source_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
