# Generated by Django 5.2.1 on 2025-09-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_alter_shipment_truck_alter_shipment_yard_hdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgoodsissue',
            name='shipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pgis', to='rf_dispatch.shipment'),
        ),
    ]
