# Generated by Django 5.2.1 on 2025-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_remove_outbounddeliveryitem_vol_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbounddelivery',
            name='cust_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outbounddelivery',
            name='ship_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outbounddelivery',
            name='sold_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outbounddelivery',
            name='whs_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
