# Generated by Django 5.2.1 on 2025-07-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_remove_bin_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockupload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
