# Generated by Django 5.2.1 on 2025-09-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_delete_inspectionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.inspectionquestion')),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='rf_dispatch.yardhdr')),
            ],
        ),
    ]
