# Generated by Django 5.2.3 on 2025-09-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0006_alter_product_pallet_no'),
        ('rf_dispatch', '0009_alter_binlog_created_by'),
    ]

    operations = [
    ]
