# Generated by Django 5.2.1 on 2025-09-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_remove_product_pallet_no_product_pallet_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pallet_no',
        ),
        migrations.AddField(
            model_name='product',
            name='pallet_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='rf_dispatch.pallet'),
        ),
    ]
