# Generated by Django 5.2.3 on 2025-09-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_alter_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='sub_category',
        ),
    ]
