# Generated by Django 5.2.3 on 2025-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_remove_packing_picking'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
