# Generated by Django 5.2.3 on 2025-07-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0009_alter_product_product_id'),
        ('rf_dispatch', '0010_stockupload_description'),
    ]

    operations = [
    ]
