# Generated by Django 5.2.1 on 2025-06-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0010_alter_yardhdr_is_the_truck_dock_level_ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(max_length=10)),
                ('truck_date', models.DateField()),
                ('truck_time', models.TimeField()),
                ('comment', models.TextField()),
                ('status', models.CharField(default='Not planned', max_length=20)),
            ],
        ),
    ]
