# Generated by Django 5.2.3 on 2025-08-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0010_salesordercreation_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesordercreation',
            name='address',
        ),
    ]
