# Generated by Django 5.2.1 on 2025-09-05 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0010_alter_outbounddelivery_cust_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbounddeliveryitem',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outbounddeliveryitem',
            name='vol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
