# Generated by Django 5.2.3 on 2025-09-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0010_rename_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockupload',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_uploads', to='rf_dispatch.category'),
        ),
        migrations.AddField(
            model_name='stockupload',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.subcategory'),
        ),
    ]
