# Generated by Django 5.2.1 on 2025-08-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0010_salesordercreation_net_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbounddelivery',
            name='str_loc',
        ),
    ]
