# Generated by Django 5.2.1 on 2025-09-12 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0010_postgoodsissue_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentPGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.postgoodsissue')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.shipment')),
            ],
        ),
    ]
