# Generated by Django 5.2.3 on 2025-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0010_alter_inventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
