# Generated by Django 5.2.3 on 2025-08-28 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0010_picking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbounddeliveryproduct',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibdproducts', to='rf_dispatch.inbounddelivery'),
        ),
    ]
