# Generated by Django 5.2.3 on 2025-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0011_alter_inventory_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbounddelivery',
            name='carrier_info',
        ),
        migrations.RemoveField(
            model_name='inbounddelivery',
            name='gr_date',
        ),
        migrations.RemoveField(
            model_name='inbounddelivery',
            name='storage_location',
        ),
        migrations.AddField(
            model_name='inbounddelivery',
            name='esn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
