# Generated by Django 5.2.3 on 2025-09-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0011_rename_location_putaway_destination_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sorted', 'Sorted')], default='pending', max_length=50)),
                ('sorted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.outbounddelivery')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.pallet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.product')),
                ('warehouse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.warehouse')),
            ],
        ),
    ]
