# Generated by Django 5.2.1 on 2025-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0011_remove_outbounddelivery_str_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbounddelivery',
            name='whs_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
