# Generated by Django 5.2.1 on 2025-09-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0011_outbounddeliveryitem_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbounddeliveryitem',
            old_name='vol',
            new_name='vol_per_item',
        ),
    ]
