# Generated by Django 5.2.3 on 2025-09-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0011_stockupload_category_stockupload_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockupload',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stockupload',
            name='sub_category',
        ),
    ]
