# Generated by Django 5.2.1 on 2025-06-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0011_trucklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucklog',
            name='truck_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.yardhdr', to_field='truck_no'),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='truck_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
