# Generated by Django 5.2.1 on 2025-09-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0011_shipmentpgi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentPGI',
        ),
    ]
