# Generated by Django 5.2.3 on 2025-07-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_customers_inventory_vendor_product_action_pallet copy'),
        ('rf_dispatch', '0003_purchaseorder copy'),
        ('rf_dispatch', '0012_remove_product_action_customers_vendor_id_and_more'),
    ]

    operations = [
    ]
