# Generated by Django 5.2.3 on 2025-08-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0012_alter_inbounddeliveryproduct_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbounddeliveryproduct',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rf_dispatch.inbounddelivery'),
        ),
        migrations.AlterField(
            model_name='inbounddeliveryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_deliveries', to='rf_dispatch.product'),
        ),
    ]
