# Generated by Django 5.2.1 on 2025-09-16 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0012_delete_shipmentpgi'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
