# Generated by Django 5.2.1 on 2025-09-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0012_rename_vol_outbounddeliveryitem_vol_per_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgoodsissue',
            options={'ordering': ['-posting_date'], 'verbose_name': 'Post Goods Issue', 'verbose_name_plural': 'Post Goods Issues'},
        ),
    ]
