# Generated by Django 5.2.1 on 2025-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0012_alter_trucklog_truck_no_alter_yardhdr_truck_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardhdr',
            name='truck_no',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
