# Generated by Django 5.2.3 on 2025-09-16 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0012_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorting',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='rf_dispatch.salesordercreation'),
            preserve_default=False,
        ),
    ]
