# Generated by Django 5.2.3 on 2025-07-23 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0013_merge_20250722_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='action',
        ),
        migrations.AddField(
            model_name='customers',
            name='vendor_id',
            field=models.CharField(default=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(max_length=100),
        ),
    ]
