# Generated by Django 5.2.3 on 2025-09-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0013_sorting_sales_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorting',
            old_name='sales_order',
            new_name='so_no',
        ),
    ]
