# Generated by Django 5.2.1 on 2025-06-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0013_alter_yardhdr_truck_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucklog',
            old_name='truck_no',
            new_name='truck_no_id',
        ),
    ]
