# Generated by Django 5.2.3 on 2025-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0014_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockupload',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockupload',
            name='sub_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
