# Generated by Django 5.2.3 on 2025-09-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0014_rename_sales_order_sorting_so_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorting',
            name='so_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.salesordercreation'),
        ),
    ]
