# Generated by Django 5.2.3 on 2025-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0015_stockupload_category_stockupload_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='category',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='sub_category',
            field=models.CharField(blank=True, null=True),
        ),
    ]
