# Generated by Django 5.2.3 on 2025-09-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0015_alter_sorting_so_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorting',
            name='so_no',
        ),
    ]
