# Generated by Django 5.2.1 on 2025-06-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0015_rename_truck_no_id_trucklog_truck_no_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucklog',
            old_name='truck_no_i',
            new_name='truck_no',
        ),
    ]
