# Generated by Django 5.2.3 on 2025-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0016_alter_stockupload_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='batch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='doc_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='inspection',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='pallet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='pallet_status',
            field=models.CharField(default='Not planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='stock_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='whs_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='wps',
            field=models.CharField(max_length=50),
        ),
    ]
