# Generated by Django 5.2.1 on 2025-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0016_rename_truck_no_i_trucklog_truck_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardhdr',
            name='driver_phn_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='po_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='seal_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='truck_status',
            field=models.CharField(default='Not planned', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='truck_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='yardhdr',
            name='yard_scan',
            field=models.CharField(max_length=10),
        ),
    ]
