# Generated by Django 5.2.3 on 2025-09-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0017_alter_stockupload_batch_alter_stockupload_doc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockupload',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.bin'),
        ),
    ]
