# Generated by Django 5.2.3 on 2025-09-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0011_shipmentpgi'),
        ('rf_dispatch', '0017_sorting_so_no'),
    ]

    operations = [
    ]
