# Generated by Django 5.2.1 on 2025-06-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0018_trucklog_status_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trucklog',
            name='truck_date',
        ),
        migrations.RemoveField(
            model_name='trucklog',
            name='truck_time',
        ),
    ]
