# Generated by Django 5.2.3 on 2025-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0018_merge_0011_shipmentpgi_0017_sorting_so_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorting',
            options={'ordering': ['-sorted_at']},
        ),
        migrations.AddField(
            model_name='sorting',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sorting',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sorted', 'Sorted')], default='Pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='sorting',
            index=models.Index(fields=['status'], name='rf_dispatch_status_5af142_idx'),
        ),
        migrations.AddIndex(
            model_name='sorting',
            index=models.Index(fields=['outbound'], name='rf_dispatch_outboun_e57d4f_idx'),
        ),
    ]
