# Generated by Django 5.2.3 on 2025-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0018_alter_stockupload_batch_alter_stockupload_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='bin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
