# Generated by Django 5.2.1 on 2025-06-24 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0019_remove_trucklog_truck_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucklog',
            name='truck_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trucklog',
            name='truck_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
