# Generated by Django 5.2.3 on 2025-09-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0019_alter_sorting_options_sorting_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorting',
            options={'ordering': ['location']},
        ),
    ]
