# Generated by Django 5.2.1 on 2025-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0020_trucklog_truck_date_trucklog_truck_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucklog',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trucklog',
            name='truck_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trucklog',
            name='truck_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
