# Generated by Django 5.2.3 on 2025-09-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0020_alter_stockupload_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='whs_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.warehouse'),
        ),
    ]
