# Generated by Django 5.2.1 on 2025-09-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_inventory_product'),
        ('rf_dispatch', '0021_alter_stockupload_whs_no'),
    ]

    operations = [
    ]
