# Generated by Django 5.2.1 on 2025-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0021_alter_trucklog_comment_alter_trucklog_truck_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpload',
            fields=[
                ('whs_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('batch', models.CharField(max_length=20)),
                ('bin', models.CharField(max_length=20)),
                ('pallet', models.CharField(max_length=20)),
                ('p_mat', models.CharField(max_length=20)),
                ('inspection', models.CharField(max_length=20)),
                ('stock_type', models.CharField(max_length=20)),
                ('wps', models.CharField(max_length=20)),
                ('doc_no', models.CharField(max_length=20)),
                ('pallet_status', models.CharField(default='Not planned', max_length=20)),
            ],
        ),
    ]
