# Generated by Django 5.2.1 on 2025-06-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0022_stockupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_phn_no', models.CharField(max_length=10)),
                ('truck_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.yardhdr', to_field='truck_no')),
            ],
        ),
    ]
